[package]
name = "solve_problem"
version = "0.1.0"
authors = ["Joseph Mate <mate.joseph@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
